language: python
matrix:
  include:
  - python: '3.6'
    env: TOXENV=py36
install:
- pip install tox
script:
- tox
deploy:
  provider: pypi
  user: jcechovsky
  password:
    secure: Dg1krYMr/Am/bJpFFr36uq2azWTsilR92f9iKit70t9XFYJP04DLFZ16/nwaik3m05Qi2YdEUVkL7VyvefV1FTdACr5mjRd8no+999cNmcpfx/d5w0GUn30qoQcaZn6JL3GSMaxf0R1bPfMVSbqIklCrrUJpWp8HFf62+fTwl3YBtAO9uddHyTnfDHnttcXCZG2LMEtf3ltW4y0ZT7rxgtDZh+x3UFz1uZBdjIs64hn5amWCo0LrxMLiJ3MCki3UxFjt5OnW/vzSXyrwIt6EVDbYBGv6qbMzLnDcrngPLOayy1elxQI7UdQutpFlCRHh7Vuy/mkjG0hoqUk7sVErDAfYL18Ce+Ff1ypIxn5GnltUv2tniV3gSSQk6O+VXOcspBNtcubVA/+iH9iNnwJxDqeKeMJRYaNgWLH5pzkwYgl45tflAkdG83L8kwF8eWA7awV+zKfNnRAr5oObuizqZxUb94yMJc/Mxt3PnwzP8QXXI1VJC5fQEhQKsf2gBNwazdzEzR0Wxk3x/9g8VfOTooL+lwUVWYr1NjksSniN/L6GQsXRQkseJ11efrLOzd8jAag7HT4wYo6jkM0xJYi2VcdfAj8Lu/ZkJQEZrL3zTeDaHCbM1mybDY5PMPbdcLG+y1S+ZB5EPjIHRhHRLhE/CR0qRLlwAcP+b2SrAi31rnc=
  on:
    tags: true