language: python
matrix:
  include:
  - python: '3.6'
    env: TOXENV=py36
install:
- pip install tox
script:
- tox
deploy:
  provider: pypi
  user: jcechovsky
  password: PYPI_PASSWORD
env:
  global:
    secure: jw8zR6LapW19CK5BwZTG9IN6a97W9+YvXzuaUwoPAqsIz/6n/d2efH8x4/757nrLDOGC2VpDwFgeyFtUckmz9i0d7OKAICUZkufLkNQkMYvi/mmunu+nR+tXFlqJYgezRnnFqBrj7A+IT5fIaQeEbLN3dAIAglB6/1x5sgvSlvUxwXlljPMWN8yIzClhPgogE2rRN2fWB60bVvCSVgMmUfKILTXvLLXIMbL0YujaTm3AeMRAj2RCf40e8Gvp0vmkHtLX3Vwcy1mkt05ChAmEcS+Sts/Jl9d26nY5nyg7qMvWeyFE67sdapXkmvjHMJFemmwHVu0l+MdcNQWoMUculUniyOw0o7EFQ4hR6C6VAXO/zViF0ppLVqb9jy/4Qsc2srIxJ9Nco9xORXaDPpAPWNouHaGzxJPsWw72qqsWxcbRaEgK9Iny/bL+/gsDb5UnBY/szVJk0vUu3QqMye28Qw6CtrAiYdn11Itno9YqWUFmkPOHwtouNzgxs/Jkb+agczPEwjZZe3CPJFdwBBcbz04qm6qzL8FDXzhw+5W4qhqKR6DsVxsrAv5razFjgX0vC4b7ZrM6hpdDXtq5zU9EBW4R+qAVVe0f14VED68RAWm7uWtkoyYB4wpq6yAUOYjAhZWHI6DvzTQ9zrKf6mwT6bppNNr+xcGsZFrfiwSu93M=
